-- MySQL Script generated by MySQL Workbench
-- mar 08 nov 2016 20:44:20 COT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`product_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product_type` (
  `id_product_type` INT NOT NULL,
  `name_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_product_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producto` (
  `id_product` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `warranty` INT(11) NOT NULL,
  `observation` VARCHAR(45) NULL,
  `status` VARCHAR(45) NOT NULL,
  `product_type_id_product_type` INT NOT NULL,
  PRIMARY KEY (`id_product`, `product_type_id_product_type`),
  UNIQUE INDEX `id_producto_UNIQUE` (`id_product` ASC),
  INDEX `fk_producto_product_type_idx` (`product_type_id_product_type` ASC),
  CONSTRAINT `fk_producto_product_type`
    FOREIGN KEY (`product_type_id_product_type`)
    REFERENCES `mydb`.`product_type` (`id_product_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

/*public function up()
    {
        Schema::create('products', function (Blueprint $table) {
            $table->increments('id_product');
            $table->string('name');
            $table->string('warranty');
            $table->text('observation');
            $table->string('status');
            $table->integer('product_type_id')->unsigned();
            $table->foreign('product_type_id')->references('id_type')->on('product_types');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('products');
    }*/
