INSERT INTO `products` (`id`, `name`, `warranty`, `observation`, `product_type_id`, `status`, `reference`, `created_at`, `updated_at`, `trademark`, `quantity`, `presentation`) VALUES 
('4','Ungüento Anestesico','','','2','E', '',NULL,NULL,'Gaia','2','P'),
('5','Agujas 25x40','','','2','E', '',NULL,NULL,'Shen Long Pai','12','P'),
('6','Agujas 22x13','','','2','E', '',NULL,NULL,'Shen Long Pai','2','P'),
('7','Agujas 22x25','','','2','E', '',NULL,NULL,'Shen Long Pai','4','P'),
('8','Estimulo','','','2','E', '',NULL,NULL,'Bledkar','3x50','P'),
('9','Silla ','','','1','B', '',NULL,NULL,'','9','P'),
('10','Silla Ruedas','','','1','B', '',NULL,NULL,'','2','P'),
('11','Equipo Plata Liquida','','','2','B', '',NULL,NULL,'','1','P'),
('12','Equipo Desintoxicacion','','','2','B', '',NULL,NULL,'','1','P'),
('13','Fajas Desintoxicacion','','','2','B', '',NULL,NULL,'','2','P'),
('14','Manillas Desintoxicacion','','','2','B', '',NULL,NULL,'','2','P'),
('15','Electrodo','','','2','B', '',NULL,NULL,'','4','P'),
('16','Camilla','','','1','B', '',NULL,NULL,'','4','P'),
('17','Cobija','','','1','B', '',NULL,NULL,'','3','P'),
('18','Escritorio Madera','','','1','B', '',NULL,NULL,'','2','P'),
('19','Escritorio Vidrio','','','1','B', '',NULL,NULL,'','1','P'),
('20','Sofá','','','1','B', '',NULL,NULL,'','3','P'),
('21','Mesa Centro','','','1','B', '',NULL,NULL,'','1','P'),
('22','Dispensador Agua','','','1','E', '',NULL,NULL,'Electrolux','1','P'),
('23','Televisor','','','1','B', '',NULL,NULL,'Samsung','1','P'),
('24','Recipiente Basura Grande Plastico','','','1','B', '',NULL,NULL,'Vanyplas','8','P'),
('25','Recipiente Basura Pequeño Plastico','','','1','B', '',NULL,NULL,'Vanyplas','2','P'),
('26','Recipiente Basura Pequeño Aluminio','','','2','B', '',NULL,NULL,'','1','P'),
('27','Peso','','','2','B', '',NULL,NULL,'','1','P'),
('28','Computador','','','1','B', '',NULL,NULL,'hp','1','P'),
('29','BlueRay','','','1','E', '',NULL,NULL,'Samsung','1','P'),
('30','Equipo Electroacupuntura','','','2','B', '',NULL,NULL,'','1','P'),
('31','Pointer','','','2','B', '',NULL,NULL,'','2','P'),
('32','Algodonera Aluminio','','','2','B', '',NULL,NULL,'','3','P'),
('33','Pinzas','','','2','B', '',NULL,NULL,'','1','P'),
('34','Tijeras','','','2','B', '',NULL,NULL,'','1','P'),
('35','Escoba','','','1','B', '',NULL,NULL,'','1','P'),
('36','Trapero','','','1','B', '',NULL,NULL,'','1','P'),
('37','Recogedor','','','1','B', '',NULL,NULL,'','1','P'),
('38','Balde','','','1','B', '',NULL,NULL,'','2','P'),
('39','Recipiente para Desintoxicacion','','','2','B', '',NULL,NULL,'','4','P'),
('40','Moxario Sencillo','','','2','B', '',NULL,NULL,'','1','P'),
('41','Moxario Doble','','','2','B', '',NULL,NULL,'','1','P'),
('42','Moxario Bajo por 5','','','2','B', '',NULL,NULL,'','2','P'),
('43','Moxario Bajo por 1','','','2','B', '',NULL,NULL,'','4','P'),
('44','Bolas Relajantes','','','2','B', '',NULL,NULL,'','2','P'),
('45','Dispensador Alcohol','','','2','B', '',NULL,NULL,'','3','P'),
('46','Guardian','','','2','B', '',NULL,NULL,'','3','P'),
('47','Escalerillas','','','1','B', '',NULL,NULL,'Vanyplas','4','P'),
('48','Calentador','','','1','B', '',NULL,NULL,'','1','P'),
('49','Grapadora','','','1','B', '',NULL,NULL,'Wingo','1','P'),
('50','Tijeras','','','1','B', '',NULL,NULL,'','1','P'),
('51','Perforadora','','','1','B', '',NULL,NULL,'Wingo','1','P'),
('52','Archivador','','','1','B', '',NULL,NULL,'','3','P'),
('53','Nux Vómica 6-D L.H.H','','','2','E', '',NULL,NULL,'Hering','2','P'),
('54','Discus 12-D L.H.H','','','2','E', '',NULL,NULL,'Hering','1','P'),
('55','Symphytum 6-D L.H.H','','','2','E', '',NULL,NULL,'Hering','1','P'),
('56','Drosera 6-D L.H.H','','','2','E', '',NULL,NULL,'Hering','3','P'),
('57','Ignatia 6-D L.H.H','','','2','E', '',NULL,NULL,'Hering','1','P'),
('58','Echinacea 6-D L.H.H','','','2','E', '',NULL,NULL,'Hering','5','P'),
('59','Adelgazante Complex','','','2','E', '',NULL,NULL,'Hering','3','P'),
('60','Biofort L.H.H','','','2','E', '',NULL,NULL,'Hering','4','P'),
('61','Luffa Oper L.H.H','','','2','E', '',NULL,NULL,'Hering','4','P'),
('62','Dispensador Toallas','','','1','E', '',NULL,NULL,'Familia','2','P'),
('63','Dispensador Papel Higienico','','','1','E', '',NULL,NULL,'Familia','2','P'),
('64','Dispensador Jabon de Manos','','','1','E', '',NULL,NULL,'Familia','2','P'),
('65','Caja Ventosas','','','2','E', '',NULL,NULL,'','1','P'),
('66','Pebetero','','','2','E', '',NULL,NULL,'','1','P'),
('67','Carrito Aluminio con Cajones','','','1','B', '',NULL,NULL,'','1','P'),
('68','Carrito Aluminio sin Cajones','','','1','B', '',NULL,NULL,'','1','P'),
('69','Carrito Plastico Con Cajones','','','1','B', '',NULL,NULL,'','1','P'),
('70','Carrito Plastico sin Cajones','','','1','B', '',NULL,NULL,'','1','P')
